# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V9IQb50Nb5vOmY1KWdm7Q0xRMjQBcivn
"""

print("hello python")